-- https://www.mockaroo.com/

create table customers (
	id INT primary key,
	name VARCHAR(50),
	city VARCHAR(50),
	country VARCHAR(50)
);
insert into customers (id, name, city, country) values (1, 'Alfreds Futterkiste', 'Futterkiste', 'Germany');
insert into customers (id, name, city, country) values (2, 'Ana Trujillo Emparedados y helados', 'Trujillo', 'Spain');
insert into customers (id, name, city, country) values (3, 'Antonio Moreno Taqueria', 'Cazorla', 'Spain');
insert into customers (id, name, city, country) values (4, 'Around the Horn', 'Boston', 'United States');
insert into customers (id, name, city, country) values (5, 'Berglunds snabbkop', 'Halle', 'Germany');
insert into customers (id, name, city, country) values (6, 'Blauer See Delikatessen', 'Lisbon', 'Portugal');
insert into customers (id, name, city, country) values (7, 'Blondel pere et fils', 'Tours', 'France');
insert into customers (id, name, city, country) values (8, 'Bolido Comidas preparadas', 'Almagro', 'Spain');
insert into customers (id, name, city, country) values (9, 'Bon app', 'Pescara', 'Italy');
insert into customers (id, name, city, country) values (10, 'Bottom-Dollar Marketse', 'Savannah', 'United States');
insert into customers (id, name, city, country) values (11, 'Mydo', 'Nantes', 'France');
insert into customers (id, name, city, country) values (12, 'Izio', 'Vila Ribeiro', 'Portugal');
insert into customers (id, name, city, country) values (13, 'Katz', 'Alminhas', 'Portugal');
insert into customers (id, name, city, country) values (14, 'Pixope', 'Boston', 'United States');
insert into customers (id, name, city, country) values (15, 'Skajo', 'Halle', 'Germany');
insert into customers (id, name, city, country) values (16, 'Flashdog', 'Casal', 'Portugal');
insert into customers (id, name, city, country) values (17, 'Linkbuzz', 'Santarém', 'Portugal');
insert into customers (id, name, city, country) values (18, 'Meembee', 'Tours', 'France');
insert into customers (id, name, city, country) values (19, 'Zoozzy', 'Pescara', 'Italy');
insert into customers (id, name, city, country) values (20, 'Avavee', 'Savannah', 'United States');
insert into customers (id, name, city, country) values (21, 'Voolith', 'Messina', 'Italy');
insert into customers (id, name, city, country) values (22, 'Quinu', 'Denver', 'United States');
insert into customers (id, name, city, country) values (23, 'Divape', 'Sacramento', 'United States');
insert into customers (id, name, city, country) values (24, 'Talane', 'Estrada', 'Portugal');
insert into customers (id, name, city, country) values (25, 'Linklinks', 'Amiens', 'France');
insert into customers (id, name, city, country) values (26, 'Zoomzone', 'Ceuta', 'Spain');
insert into customers (id, name, city, country) values (27, 'Photofeed', 'Vagney', 'France');
insert into customers (id, name, city, country) values (28, 'Fanoodle', 'Arganil', 'Portugal');
insert into customers (id, name, city, country) values (29, 'Wikivu', 'Peras Ruivas', 'Portugal');
insert into customers (id, name, city, country) values (30, 'Meeveo', 'Pereira', 'Portugal');
insert into customers (id, name, city, country) values (31, 'Youspan', 'Sochaux', 'France');
insert into customers (id, name, city, country) values (32, 'Brainlounge', 'Alpiarça', 'Portugal');
insert into customers (id, name, city, country) values (33, 'Divanoodle', 'Balazar', 'Portugal');
insert into customers (id, name, city, country) values (34, 'Skiba', 'Dallas', 'United States');
insert into customers (id, name, city, country) values (35, 'Kare', 'São Miguel do Rio Torto', 'Portugal');
insert into customers (id, name, city, country) values (36, 'Tagfeed', 'Escola', 'Portugal');
insert into customers (id, name, city, country) values (37, 'Fivebridge', 'Épinal', 'France');
insert into customers (id, name, city, country) values (38, 'Feedfire', 'Calvão', 'Portugal');
insert into customers (id, name, city, country) values (39, 'Devcast', 'Montes', 'Portugal');
insert into customers (id, name, city, country) values (40, 'Eidel', 'Hagerstown', 'United States');
insert into customers (id, name, city, country) values (41, 'Buzzshare', 'Lille', 'France');
insert into customers (id, name, city, country) values (42, 'Kwinu', 'Portela', 'Portugal');
insert into customers (id, name, city, country) values (43, 'Edgeify', 'Detroit', 'United States');
insert into customers (id, name, city, country) values (44, 'Realmix', 'Washington', 'United States');
insert into customers (id, name, city, country) values (45, 'Dabtype', 'Niort', 'France');
insert into customers (id, name, city, country) values (46, 'Zoomdog', 'Serra D''El Rei', 'Portugal');
insert into customers (id, name, city, country) values (47, 'Topicshots', 'São Domingos', 'Portugal');
insert into customers (id, name, city, country) values (48, 'Jamia', 'Lyon', 'France');
insert into customers (id, name, city, country) values (49, 'Devbug', 'Périgueux', 'France');
insert into customers (id, name, city, country) values (50, 'Oyoyo', 'Rochester', 'United States');
insert into customers (id, name, city, country) values (51, 'Fivespan', 'Cagliari', 'Italy');
insert into customers (id, name, city, country) values (52, 'Meevee', 'Castro Daire', 'Portugal');
insert into customers (id, name, city, country) values (53, 'Cogidoo', 'Pinhal Novo', 'Portugal');
insert into customers (id, name, city, country) values (54, 'Eare', 'Alvito de São Pedro', 'Portugal');
insert into customers (id, name, city, country) values (55, 'Meembee', 'Cartagena', 'Spain');
insert into customers (id, name, city, country) values (56, 'Twitterworks', 'Seixal', 'Portugal');
insert into customers (id, name, city, country) values (57, 'Camido', 'Auch', 'France');
insert into customers (id, name, city, country) values (58, 'Eare', 'Niort', 'France');
insert into customers (id, name, city, country) values (59, 'Zoombeat', 'Fort Lauderdale', 'United States');
insert into customers (id, name, city, country) values (60, 'Dynava', 'Charlotte', 'United States');
insert into customers (id, name, city, country) values (61, 'Wordware', 'Wilmington', 'United States');
insert into customers (id, name, city, country) values (62, 'Jayo', 'Ardazubre', 'Portugal');
insert into customers (id, name, city, country) values (63, 'Feedbug', 'Dayton', 'United States');
insert into customers (id, name, city, country) values (64, 'Tagopia', 'Beaumont', 'United States');
insert into customers (id, name, city, country) values (65, 'Twitterlist', 'Stuttgart Stuttgart-Mitte', 'Germany');
insert into customers (id, name, city, country) values (66, 'Wordify', 'Saint-Amand-les-Eaux', 'France');
insert into customers (id, name, city, country) values (67, 'Wikizz', 'Saint Paul', 'United States');
insert into customers (id, name, city, country) values (68, 'Yakidoo', 'Vila Nova da Baronia', 'Portugal');
insert into customers (id, name, city, country) values (69, 'Meevee', 'Rio de Moinhos', 'Portugal');
insert into customers (id, name, city, country) values (70, 'Muxo', 'Vila Flor', 'Portugal');
insert into customers (id, name, city, country) values (71, 'Podcat', 'Prior Velho', 'Portugal');
insert into customers (id, name, city, country) values (72, 'Vinte', 'Waco', 'United States');
insert into customers (id, name, city, country) values (73, 'Voomm', 'Santa Fe', 'United States');
insert into customers (id, name, city, country) values (74, 'Twinte', 'Berlin', 'Germany');
insert into customers (id, name, city, country) values (75, 'Agivu', 'Lawrenceville', 'United States');
insert into customers (id, name, city, country) values (76, 'Browsecat', 'Memphis', 'United States');
insert into customers (id, name, city, country) values (77, 'Bubbletube', 'Soito', 'Portugal');
insert into customers (id, name, city, country) values (78, 'Shufflester', 'Saint-Quentin-en-Yvelines', 'France');
insert into customers (id, name, city, country) values (79, 'Gigazoom', 'Garden Grove', 'United States');
insert into customers (id, name, city, country) values (80, 'Fadeo', 'Mobile', 'United States');
insert into customers (id, name, city, country) values (81, 'Skyble', 'Cergy-Pontoise', 'France');
insert into customers (id, name, city, country) values (82, 'Cogidoo', 'Besançon', 'France');
insert into customers (id, name, city, country) values (83, 'Rhyzio', 'Les Clayes-sous-Bois', 'France');
insert into customers (id, name, city, country) values (84, 'Brightbean', 'Zambujal', 'Portugal');
insert into customers (id, name, city, country) values (85, 'Devcast', 'Saintes', 'France');
insert into customers (id, name, city, country) values (86, 'Trilith', 'Lagoa', 'Portugal');
insert into customers (id, name, city, country) values (87, 'Fatz', 'Landim', 'Portugal');
insert into customers (id, name, city, country) values (88, 'Photospace', 'Póvoa de Penela', 'Portugal');
insert into customers (id, name, city, country) values (89, 'Dabtype', 'Vila Fria', 'Portugal');
insert into customers (id, name, city, country) values (90, 'Meedoo', 'Praia da Tocha', 'Portugal');
insert into customers (id, name, city, country) values (91, 'Kaymbo', 'Calheta de Nesquim', 'Portugal');
insert into customers (id, name, city, country) values (92, 'Pixoboo', 'Pedome', 'Portugal');
insert into customers (id, name, city, country) values (93, 'Skajo', 'El Paso', 'United States');
insert into customers (id, name, city, country) values (94, 'Katz', 'Oklahoma City', 'United States');
insert into customers (id, name, city, country) values (95, 'Skimia', 'Paris 13', 'France');
insert into customers (id, name, city, country) values (96, 'Plambee', 'Santa Iria de Azóia', 'Portugal');
insert into customers (id, name, city, country) values (97, 'Zooxo', 'Vila', 'Portugal');
insert into customers (id, name, city, country) values (98, 'Fivebridge', 'Houston', 'United States');
insert into customers (id, name, city, country) values (99, 'Voonder', 'Pouzauges', 'France');
insert into customers (id, name, city, country) values (100, 'Edgeblab', 'San Diego', 'United States');
insert into customers (id, name, city, country) values (101, 'Mycat', 'Santa Cruz', 'United States');
insert into customers (id, name, city, country) values (102, 'Muxo', 'Créteil', 'France');
insert into customers (id, name, city, country) values (103, 'Aimbo', 'Boavista', 'Portugal');
insert into customers (id, name, city, country) values (104, 'Trunyx', 'Houston', 'United States');
insert into customers (id, name, city, country) values (105, 'Feedspan', 'Saint-Jean-de-Monts', 'France');
insert into customers (id, name, city, country) values (106, 'Brainverse', 'Paris 13', 'France');
insert into customers (id, name, city, country) values (107, 'Bubblebox', 'Paris 09', 'France');
insert into customers (id, name, city, country) values (108, 'Twimbo', 'Achada', 'Portugal');
insert into customers (id, name, city, country) values (109, 'Yakijo', 'Boavista', 'Portugal');
insert into customers (id, name, city, country) values (110, 'Einti', 'Redinha', 'Portugal');
